services:
  - type: web
    name: invoices-api
    runtime: dotnet
    buildCommand: "dotnet publish Invoices.Api/Invoices.Api.csproj -c Release -o out"
    startCommand: "dotnet out/Invoices.Api.dll"
    envVars:
      - key: ASPNETCORE_URLS
        value: "http://0.0.0.0:$PORT"
        
  - type: web
    name: invoices-blazor
    runtime: dotnet
    buildCommand: "dotnet publish Invoices.Blazor/Invoices.Blazor.csproj -c Release -o out"
    startCommand: "dotnet out/Invoices.Blazor.dll"
    envVars:
      - key: ASPNETCORE_URLS
        value: "http://0.0.0.0:$PORT"
