services:
  - type: web
    name: invoices-api
    runtime: dotnet
    buildCommand: "dotnet publish Invoices.Api/Invoices.Api.csproj -c Release -o out"
    startCommand: "dotnet out/Invoices.Api.dll"
    envVars:
      ASPNETCORE_URLS: "http://0.0.0.0:10000"

  - type: web
    name: invoices-blazor
    runtime: dotnet
    buildCommand: "dotnet publish Invoices.Blazor/Invoices.Blazor.csproj -c Release -o out"
    startCommand: "dotnet out/Invoices.Blazor.dll"
    envVars:
      ASPNETCORE_URLS: "http://0.0.0.0:10001"
